============================================================
  Generated by:           Genus(TM) Synthesis Solution 17.22-s017_1
  Generated on:           Dec 03 2021  05:08:35 pm
  Module:                 upcounter
  Technology library:     tsmc18 1.0
  Operating conditions:   slow (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

                              
   Gate    Instances   Area    Library  
----------------------------------------
AND2X1             2   26.611    tsmc18 
AOI2BB1XL          2   33.264    tsmc18 
DFFRHQX1           3  209.563    tsmc18 
INVXL              2   13.306    tsmc18 
JKFFRXL            1   86.486    tsmc18 
----------------------------------------
total             10  369.230           


                                        
     Type      Instances   Area  Area % 
----------------------------------------
sequential             4 296.050   80.2 
inverter               2  13.306    3.6 
logic                  4  59.875   16.2 
physical_cells         0   0.000    0.0 
----------------------------------------
total                 10 369.230  100.0 

