============================================================
  Generated by:           Genus(TM) Synthesis Solution 17.22-s017_1
  Generated on:           Dec 03 2021  05:09:11 pm
  Module:                 upcounter
  Technology library:     tsmc18 1.0
  Operating conditions:   slow (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

                 Leakage   Dynamic    Total   
 Instance Cells Power(nW) Power(nW) Power(nW) 
----------------------------------------------
upcounter    10    11.461 10372.853 10384.314 

