
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Dec  3 2021 17:07:54 IST (Dec  3 2021 11:37:54 UTC)

// Verification Directory fv/upcounter 

module upcounter(clk, reset, counter);
  input clk, reset;
  output [3:0] counter;
  wire clk, reset;
  wire [3:0] counter;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5;
  JKFFRXL \counter_up_reg[3] (.RN (n_4), .CK (clk), .J (n_5), .K (n_5),
       .Q (counter[3]), .QN (UNCONNECTED));
  DFFRHQX1 \counter_up_reg[2] (.RN (n_4), .CK (clk), .D (n_3), .Q
       (counter[2]));
  AOI2BB1XL g100__8780(.A0N (n_1), .A1N (counter[2]), .B0 (n_5), .Y
       (n_3));
  DFFRHQX1 \counter_up_reg[1] (.RN (n_4), .CK (clk), .D (n_2), .Q
       (counter[1]));
  AOI2BB1XL g103__4296(.A0N (counter[0]), .A1N (counter[1]), .B0 (n_1),
       .Y (n_2));
  AND2X1 g102__3772(.A (n_1), .B (counter[2]), .Y (n_5));
  DFFRHQX1 \counter_up_reg[0] (.RN (n_4), .CK (clk), .D (n_0), .Q
       (counter[0]));
  AND2X1 g105__1474(.A (counter[0]), .B (counter[1]), .Y (n_1));
  INVXL g107(.A (counter[0]), .Y (n_0));
  INVXL g106(.A (reset), .Y (n_4));
endmodule

